name: Update Docker Hub Description

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/caddy-cloudflare

jobs:
  update-description:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          readme-filepath: ./README.md
